### ISSUE TITLE
TypeError: build() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by aaronmack** [bsavery/ray-tracing-one-weekend-taichi#1]
# python main.py

```bash
[Taichi] mode=release
[Taichi] version 0.7.29, llvm 10.0.0, commit 7b40a962, win, python 3.7.7
[TaiGLSL] version 0.0.11
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    world.commit()
  File "C:\DEV_PROJECT\dev-repository\ray-tracing-one-weekend-taichi\hittable.py", line 83, in commit
    self.bvh.build(self.spheres)
TypeError: build() takes 1 positional argument but 2 were given
```

**Comment by bsavery** [comment]
Fixed with https://github.com/bsavery/ray-tracing-one-weekend-taichi/commit/0111c3df29563d8660d90fe298b9de399b86c119
